### PR TITLE
Adds 'yo' as a peerDependency

### PR DESCRIPTION
**Pull request by addyosmani**
As `yo` specifies `grunt-cli` and `bower` as peerDependencies, this should allow a `npm install -g generator-flight` to install all three of them globally. Users will no longer need to install them separately prior.

### CODE REVIEW

**Comment by necolas** [comment]
Thanks. I'm going to make a few additional changes for this.

Do you think Karma should be added as a peer dependency? It's not technically needed by the package, but the generated application workflow works best with Karma globally installed.

**Comment by passy** [comment]
Karma is a tricky one because of the two incompatible version lines. If you don't specify a version, you may run into the problem of a user having 0.9.x which is incompatible with the 0.8.x config files. If you _do_ specify a version, installing generator-flight could just abort with EPEERINVALID.

**Comment by necolas** [comment]
It shouldn't matter which version is globally installed as long as it can run a local installation. It functions a bit like `grunt-cli`. The packages themselves specify the local version of Karma to use.

**Comment by passy** [comment]
I wasn't aware of that feature. In that case adding it as peerDep sounds
like a good idea.

**Comment by passy** [comment]
This has been integrated. I guess you can close this one, @necolas.

**Pull request closed without merging**
