### PR TITLE
Change path to jQuery

### PR DESCRIPTION
**Pull request by gaqzi**
The latest version of jQuery available on Bower has moved `jquery.js` to `dist/jquery.js`.

I noticed this when I ran the generator and it failed to find the path to jQuery.

### CODE REVIEW

**Comment by necolas** [comment]
The problem is going to be that if someone needs to use 1.9, the path will be different. This is a problem because Bower doesn't automatically alias entry files.

**Comment by tbrd** [comment]
Currently when you install a new app, karma fails because the path is wrong. Surely we need to update the path, or force a specific version of jQuery?

**Comment by necolas** [comment]
Or fix bower, or not use bower :)

**Comment by angus-c** [comment]
@tbrd yep had the same issue in flight and changed the dependency path in karma conf (and that was all)

**Comment by necolas** [comment]
Should be fixed now. Install 0.7.2 of the generator, which will install jQuery 2.x by default. If someone wants 1.9 for support IE 8, they can change the paths manually.

**Pull request closed without merging**
