### PR TITLE
Implementation of package generator and supporting changes

### PR DESCRIPTION
**Pull request by necolas**
A bunch of changes to reorganize the dir structure to support the addition of a separate generator for creating Flight component packages.

cc @cameronhunter

### CODE REVIEW

**Comment by necolas** [comment]
Oops, I need to rebase the "Add `flight:package` templates" commit because I got the READMEs for the application/package the wrong way around.

**Comment by cameronhunter** [comment]
Is it weird that we append `flight-` onto the name? I imagine I'll always end up with `flight-flight-storage`. Perhaps we could just recommend that the user prepends `flight-` to their package name.

**Comment by necolas** [comment]
We already automatically add `with_` to mixins as a convenience. It would also be better to have files called things like `storage.js` and `storage.spec.js` rather than `flight-storage.js`, etc. This seems pretty nice to me:

```
yo flight:package storage
```

**Comment by necolas** [comment]
I've fixed that issue with the READMEs.

**Comment by cameronhunter** [comment]
Fair comments – I certainly agree that the implementation and spec files shouldn't include the `flight-` prefix. #shipit

**Comment by necolas** [comment]
Cool. Thanks for reviewing it. I guess you'll notice any kinks in the generator when you next write a component ;)

**Pull request merged**
